"""Add missing station columns for status tracking

Revision ID: 1a3c365d0d0d
Revises: 18d7c8ab0a3c
Create Date: 2025-08-31 03:13:30.359579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3c365d0d0d'
down_revision = '18d7c8ab0a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('current_ticket', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('current_agent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('queue_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('avg_wait_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_stations_current_agent_id', 'agents', ['current_agent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_stations_current_agent_id', type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('avg_wait_time')
        batch_op.drop_column('queue_count')
        batch_op.drop_column('current_agent_id')
        batch_op.drop_column('current_ticket')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
