"""Add is_active field to Citizen model

Revision ID: 21984da072f0
Revises: 1a3c365d0d0d
Create Date: 2025-09-01 17:43:25.064595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21984da072f0'
down_revision = '1a3c365d0d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_column('avg_wait_time')
        batch_op.drop_column('queue_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queue_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('avg_wait_time', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('citizens', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
