"""Add pre_enrollment_code field to Citizen model

Revision ID: 986f000fe331
Revises: 21984da072f0
Create Date: 2025-09-02 02:14:31.679015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986f000fe331'
down_revision = '21984da072f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizens', schema=None) as batch_op:
        batch_op.alter_column('pre_enrollment_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_citizens_pre_enrollment_code'), ['pre_enrollment_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citizens_pre_enrollment_code'))
        batch_op.alter_column('pre_enrollment_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
